// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HouseListItemV1: typeof import('./src/components/house-list-item-v1/index.vue')['default']
    HouseListItemV2: typeof import('./src/components/house-list-item-v2/index.vue')['default']
    HouseListV1: typeof import('./src/components/house-list-v1/index.vue')['default']
    HouseListV2: typeof import('./src/components/house-list-v2/index.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    TabBarItem: typeof import('./src/components/tab-bar/tab-bar-item.vue')['default']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexAnchorindex: typeof import('vant/es')['IndexAnchorindex']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
